/** Generated by TAP **/
KISSY.config({
    "modules": {
        "csst/index.xtpl": {
            "requires": [
                "kg/xtemplate/4.1.4/runtime"
            ]
        }
    },
    "packages": {
        "csst": {
            "debug": true,
            "ignorePackageNameInUri": true,
            "version": "1.0.0",
            "path": "//g.alicdn.com/tm/csst/1.0.0/",
            "group": "tm"
        },
        "kissy": {
            "base": "//g.alicdn.com/kissy/k/1.4.14/",
            "version": "1.4.14"
        }
    },
    "combine": true,
    "group": "tm"
});